# Default values for Ferrite CMS.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

# The name of the app to be shown on web pages
appName: "ferritecms"

# The production environment (should always be production)
appEnv: "production"

# Weather or not the app showa detailed error messages
appDebug: "false"

# The URL where the app can be reached
appUrl: "http://localhost"

# Weather or not to use an external secret for the app key
appKeySecret:
  useExistingSecret: false
  existingSecretName: ""
  appKey: ""

# Initial admin user settings
initialAdminUser:
  name: "admin"
  email: "admin@example.com"
  password: "ChangeMeNow!"

  existingSecretName: ""
  nameKey: "name"
  emailKey: "email"
  passwordKey: "password"

# Log settings
logChannel: "stack"
logLevel: "warning"

# The database connection settings
db:
  connection: "pgsql"
  host: "ferrite-postgres"
  port: "5432"
  database: "ferrite"
  username: "ferrite-user"
  password: "ReallyStrongPassword"

# The cache, session and queue drivers
cache:
  driver: "redis"
session:
  driver: "redis"
queue:
  connection: "redis"

# The redis connection settings
redis:
  client: "predis"
  host: "ferrite-redis"
  password: ""
  port: "6379"

# The mail settings
mail:
  mailer: "smtp"
  host: "smtp.mailtrap.io"
  port: "2525"
  username: "null"
  password: "null"
  encryption: "null"
  from: 
    address: "null"
    name: "null"

# Persistent volume settings
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 1Gi

# Where to pull static images/files
imageCdnUrl: "null"
cdnUrl: "null"

image:
  repository: harbor.artichokenetwork.com/ferritecms/ferrite
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

