{{- if not .Values.initialAdminUser.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ferritecms.fullname" . }}-initial-admin-user
  labels:
    {{- include "ferritecms.labels" . | nindent 4 }}
type: Opaque
data:
  name: {{ .Values.initialAdminUser.name | b64enc }}
  email: {{ .Values.initialAdminUser.email | b64enc }}
  password: {{ .Values.initialAdminUser.password | b64enc }}
{{- end }}